import images from "../assets";

const data = [
  {
    id: 1,
    title: "milk",
    name: "Sữa Chua Phúc Bồn Tử Đác Cam",
    price: "70.000 đ",
    start: 5,
    url: images.dau_da_xay,
  },
  {
    id: 2,
    title: "Tea",
    name: "Longan Tea (Lotus)",
    price: "50.000 đ",
    start: 5,
    url: images.travai,
  },
  {
    id: 3,
    title: "Tea",
    name: "Longan Tea (Jasmine)",
    price: "45.000 đ",
    start: 5,
    url: images.trasua,
  },
  {
    id: 4,
    title: "Milk",
    name: "Phuc Long Black Milk Tea",
    price: "45.000 đ",
    start: 5,
    url: images.traolong,
  },
  {
    id: 5,
    title: "Tea",
    name: "Phuc Long Peach Tea",
    price: "45.000 đ",
    start: 5,
    url: images.tradau,
  },
  {
    id: 6,
    title: "coffee",
    name: "Ngọc Viễn Đông",
    price: "45.000 đ",
    start: 5,
    url: images.bacxiu,
  },
  {
    id: 7,
    title: "coffee",
    name: "Phin Sữa Đá - Năng Lượng",
    price: "45.000 đ",
    start: 5,
    url: images.caphesua,
  },
  {
    id: 8,
    title: "Milk",
    name: "Trà Sữa Berry Berry",
    price: "54.000 đ",
    start: 5,
    url: images.dau_da_xay,
  },
  {
    id: 9,
    title: "Tea",
    name: "Trà Ô Long Mãng Cầu",
    price: "54.000 đ",
    start: 5,
    url: images.mangcau,
  },
];
export default data;
